
SRC=$(shell find src -name '*.hs')

{{#isyesod}}
PORT=9090
{{/isyesod}}
{{^isyesod}}
FLAGS=--enable-tests
{{/isyesod}}

all: init test docs package

init:
	cabal sandbox init
	make deps

test: build
	{{build}} test{{^isyesod}} --test-option=--color{{/isyesod}}

{{#isyesod}}
dev:
	yesod devel --port=${PORT}
{{/isyesod}}
{{^isyesod}}
specs: build
	./dist/build/{{projectName}}-specs/{{projectName}}-specs
{{/isyesod}}

run:
	cabal run

# docs:
# generate api documentation
#
# package:
# build a release tarball or executable
#
# dev:
# start dev server or process. `vagrant up`, `yesod devel`, etc.
#
# install:
# generate executable and put it into `/usr/local`
#
# deploy:
# prep and push

tags: ${SRC}
	hasktags --ctags *.hs src

hlint:
	hlint *.hs src specs

clean:
	cabal clean

distclean: clean
	cabal sandbox delete

configure: clean
	{{build}} configure ${FLAGS}

deps: clean
	cabal install --only-dependencies --allow-newer ${FLAGS}
	make configure

build:
	{{build}} build

restart: distclean init build

rebuild: clean configure build

.PHONY: all init test run clean distclean configure deps build rebuild hlint
