
SRC=$(shell find src -name '*.hs')

{{#isyesod}}
PORT=9090
{{/isyesod}}
{{^isyesod}}
{{#isjs}}
CABAL=cabal-js
{{/isjs}}
{{^isjs}}
CABAL=stack
{{/isjs}}
FLAGS=--enable-tests
{{/isyesod}}

all: init test docs package

init: stack.yaml

stack.yaml:
	stack init --prefer-nightly

test: build
	stack test

{{#isyesod}}
dev:
	yesod devel --port=${PORT}
{{/isyesod}}

run: build
	stack exec -- {{projectName}}

{{#isjs}}
open: build
	open ./dist/build/{{projectName}}/{{projectName}}.jsexe/index.html
{{/isjs}}

# docs:
# generate api documentation
#
# package:
# build a release tarball or executable
#
# dev:
# start dev server or process. `vagrant up`, `yesod devel`, etc.
#
# deploy:
# prep and push

configure:
	cabal configure --package-db=clear --package-db=global --package-db=`stack path --snapshot-pkg-db` --package-db=`stack path --local-pkg-db`

install:
	stack install

tags: ${SRC}
	codex update

hlint:
	hlint *.hs src specs

clean:
	stack clean
	codex cache clean

distclean: clean

build:
	stack build

watch:
	ghcid "--command=stack ghci"

restart: distclean init build

rebuild: clean build

.PHONY: all init configure test run clean distclean build rebuild hlint watch tags
